# Generated by Django 5.2.2 on 2025-11-16 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('product_type', models.CharField(default='standard', max_length=20)),
                ('category_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('image_path', models.CharField(max_length=500)),
                ('original_image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('orders_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('custom_button_text', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_button_url', models.CharField(blank=True, max_length=500, null=True)),
                ('like_enabled', models.BooleanField(default=True)),
                ('save_enabled', models.BooleanField(default=True)),
                ('order_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='buyer', max_length=20)),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('channel_username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('state_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=255)),
                ('message_id', models.IntegerField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_posts', to='telegram_bot.product')),
            ],
            options={
                'db_table': 'channel_posts',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='telegram_bot.user'),
        ),
        migrations.CreateModel(
            name='PostSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=255)),
                ('interval_days', models.IntegerField(default=2)),
                ('post_time', models.CharField(default='09:00', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('next_post_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='telegram_bot.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='telegram_bot.user')),
            ],
            options={
                'db_table': 'schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('buyer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_location', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_bot.product')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='telegram_bot.user')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_orders', to='telegram_bot.user')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('liked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='telegram_bot.product')),
            ],
            options={
                'db_table': 'engagements',
                'ordering': ['-created_at'],
                'unique_together': {('user_id', 'product')},
            },
        ),
    ]
